services:
  - type: web
    name: web-rtc-app
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVER_PORT
        value: 10000